### ISSUE TITLE
Pontos de atenção no projeto.

### ISSUE THREAD

**Issue by wwdaigo** [eduardoal86/easy#5]
Boa tarde. Estou na parte de avaliação do seu projeto pela Easynvest e gostaria de reforçar em alguns pontos que ficaram em desacordo com os requisitos:

- A tela de cadastro não consta no escopo do projeto. Essa é a tela de envio de contato.
- O render do formulário pelo json possui algumas propriedades que foram ignoradas. Efetuamos algumas alterações no arquivo e estas não se refletiram no resultado. Entre elas as margens e a visibilidade dos campos.

**Comment by eduardoal86** [comment]
@wwdaigo 

Bom dia! Tudo bem?

Desculpa, mas acabei não sendo notificado da issue aqui. 
Quanto a tela de cadastro criada, já foi removida. Acho que foi algum mal entendido que tive com o arquivo de layout, de alguma forma pensei que estava organizado por fluxo. Enfim, removido!

O render do formulário foi ajustado para obedecer as margens e visibilidade do campos como solicitado. 

Brigado pelos pontos!
